### ISSUE TITLE
Define multiple electrodes for anode and cathode

### ISSUE THREAD

**Issue by jessierliu** [catalystneuro/ndx-bipolar-scheme#2]
@bendichter Is it possible to define a `DynamicTableRegion` covering several electrodes for the `anode` and `cathode` columns of the `bipolar_reference_scheme`?

From the point of view of stimulation, you might spread out the `anode`, lets say, to actually be across several electrodes. However, the corresponding `cathode` would be only 1 elec. And this bipolar pair, would have 1 recorded waveform. So in the putative `StimSeries` (upcoming `ndx-electrical-stim`), we would want to map this 1d array to the row in `bipolar_reference_scheme` that may look like the first row in the below example table.

```bipolar_reference_scheme
id		anode		cathode
0		1, 2		        3
1		4			9
```

If the new bipolar `DynamicTable` could have row entries like that, then it seems like this solves both stimulation and recording purposes.

**Comment by bendichter** [comment]
Yes, this can be done. It requires making a `VectorIndex` column that targets the anode `DynamicTableRegion`. Are you sure you won't need vector cathodes as well?

**Comment by jessierliu** [comment]
Oh, hmm, so I thought that the elements of the `anode` column were `DynamicTableRegion`s themselves? Would you not be able to simply define it with more electrodes than a single one?

And sure, it could be multiple cathode, multiple anode, or single in each, I think.
