### ISSUE TITLE
Naming of DynamicTable as bipolar _reference_ scheme

### ISSUE THREAD

**Issue by jessierliu** [catalystneuro/ndx-bipolar-scheme#3]
@bendichter I wonder whether it is confusing to call it bipolar _reference_ scheme, since this initially made me think of bipolar re-referencing which is a pretty different concept since you are essentially creating artificial electrodes with perhaps artificially estimated locations, etc. Although that type of referencing would definitely practically work within what you’ve defined.

**Comment by bendichter** [comment]
I would be fine changing the name to "bipolar_scheme" if that works for everyone

**Comment by jessierliu** [comment]
I think that would be good.

@jgmakin @akhambhati @kristinksellers Any objections?

**Comment by jgmakin** [comment]
sounds good--go for it

**Comment by kristinksellers** [comment]
Good with me
